//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalaMarket.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KalaMarket.Resourses.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت نام بدون قبول قوانین امکان ندارد لطفا تیک آن را بزنید.
        /// </summary>
        public static string AcceptLaw {
            get {
                return ResourceManager.GetString("AcceptLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل وارد شده از قبل ثبت شده است از فراموشی رمز استفاده کنید.
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا ایمیل معتبر وارد نمایید.
        /// </summary>
        public static string EmailType {
            get {
                return ResourceManager.GetString("EmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته خواسته شده پدری ندارد.
        /// </summary>
        public static string ItsSelfFather {
            get {
                return ResourceManager.GetString("ItsSelfFather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این یک کلاس نیست.
        /// </summary>
        public static string NotAClass {
            get {
                return ResourceManager.GetString("NotAClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} خواسته شده پیدا نشد.
        /// </summary>
        public static string NotFind {
            get {
                return ResourceManager.GetString("NotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش منتصب شده پیدا نشد.
        /// </summary>
        public static string NotFindRole {
            get {
                return ResourceManager.GetString("NotFindRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد های رمز عبور یکسان نمیباشد.
        /// </summary>
        public static string NotSamePassword {
            get {
                return ResourceManager.GetString("NotSamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد {0} باید بین {2} و {1} حرف باشد.
        /// </summary>
        public static string OutofMinMax {
            get {
                return ResourceManager.GetString("OutofMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکلی پیش آمده است.
        /// </summary>
        public static string ProblemOccurred {
            get {
                return ResourceManager.GetString("ProblemOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این فیلد الزامی میباشد.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد {0} الزامی می‌باشد.
        /// </summary>
        public static string RequiredWithFieldName {
            get {
                return ResourceManager.GetString("RequiredWithFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش انتخاب شده نا معتبر میباشد.
        /// </summary>
        public static string RoleUnvalid {
            get {
                return ResourceManager.GetString("RoleUnvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  وارد شده نا معتبر مباشد {0}.
        /// </summary>
        public static string UnValid {
            get {
                return ResourceManager.GetString("UnValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیدی وارد شده نا معتبر است.
        /// </summary>
        public static string UnValidId {
            get {
                return ResourceManager.GetString("UnValidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور وارد شده باید حداقل شامل فقط حروف انگلیسی کوچک یا بزرگ ، حداقل یک عدد و یک کاراکتر خاص باشد ، همچنین کاراکتر خاص نباید در ابتدای رمز عبور باشد .
        /// </summary>
        public static string UnValidPassword {
            get {
                return ResourceManager.GetString("UnValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور یا ایمیل شما اشتباه است.
        /// </summary>
        public static string WrongEmailOrPassword {
            get {
                return ResourceManager.GetString("WrongEmailOrPassword", resourceCulture);
            }
        }
    }
}
