//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalaMarket.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorFluentValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorFluentValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KalaMarket.Resourses.ErrorFluentValidation", typeof(ErrorFluentValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  باید بین {From} تا {To}  حرف باشد {PropertyName} فیلد .
        /// </summary>
        public static string BetweenMinMax {
            get {
                return ResourceManager.GetString("BetweenMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باید بین {From} تا {To} حرف باشد شما {PropertyValue} وارد کردید {PropertyName} فیلد.
        /// </summary>
        public static string BetweenMinMaxWithEnteredNumber {
            get {
                return ResourceManager.GetString("BetweenMinMaxWithEnteredNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا ایمیل معتبر وارد نمایید.
        /// </summary>
        public static string EmailType {
            get {
                return ResourceManager.GetString("EmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  نمیتواند خالی یا فقط دارای فضای تهی باشد {PropertyName} فیلد .
        /// </summary>
        public static string EmptyOrWhiteSpace {
            get {
                return ResourceManager.GetString("EmptyOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   باید حداکثر {MaxLength} حرف طول داشته باشد {PropertyName} فیلد.
        /// </summary>
        public static string MaxLen {
            get {
                return ResourceManager.GetString("MaxLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  باید حداقل {MinLength} حرف طول داشته باشد {PropertyName} فیلد.
        /// </summary>
        public static string MinLen {
            get {
                return ResourceManager.GetString("MinLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد های رمز عبور یکسان نمیباشد.
        /// </summary>
        public static string NotSamePassword {
            get {
                return ResourceManager.GetString("NotSamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمیتواند نال باشد {PropertyName} فیلد.
        /// </summary>
        public static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این فیلد الزامی میباشد.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  الزامی می‌باشد {PropertyName} فیلد .
        /// </summary>
        public static string RequiredWithFieldName {
            get {
                return ResourceManager.GetString("RequiredWithFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش انتخاب شده نا معتبر میباشد.
        /// </summary>
        public static string RoleUnvalid {
            get {
                return ResourceManager.GetString("RoleUnvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  وارد شده نا معتبر مباشد {PropertyName}.
        /// </summary>
        public static string UnValid {
            get {
                return ResourceManager.GetString("UnValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور وارد شده باید حداقل شامل فقط حروف انگلیسی کوچک یا بزرگ ، حداقل یک عدد و یک کاراکتر خاص باشد ، همچنین کاراکتر خاص نباید در ابتدای رمز عبور باشد .
        /// </summary>
        public static string UnValidPassword {
            get {
                return ResourceManager.GetString("UnValidPassword", resourceCulture);
            }
        }
    }
}
